#include "I2C.h"
#include "LCD.h"
/*******************************************************************************
 * Definitions
 ******************************************************************************/
#define CO_BIT_POS				7
#define CO_BIT_COMMAND			1
#define CO_BIT_DATA				0
#define DC_BIT_POS				6
#define DC_BIT_COMMAND			0
#define DC_BIT_DATA				1
#define LCD_COMMAND				0x40
#define LCD_DISPLAY				0x00
/*******************************************************************************
 * Prototypes
 ******************************************************************************/
typedef enum CommandType{
	Setting,
	Display
}CommandType;
/*******************************************************************************
 * Variables
 ******************************************************************************/

/*******************************************************************************
 * Code
 ******************************************************************************/
bool LCD_Check(void) {
	bool Ret_bool ;
	Ret_bool = I2C2_CheckDevice(LCD_ADDRESS);
	return Ret_bool;
}

void LCD_Command(CommandType Command, uint8_t Data) {
	I2C2_Start();
	I2C2_CallAdress( (uint8_t) ((LCD_ADDRESS<<1) | I2C_WRITE));
	if (Command == Setting) {
		I2C2_Write(0x40);
	}
	else {
		I2C2_Write(0x00);
	}
	I2C2_Write(Data);
	I2C2_Stop();
}
	
void LCD_GotoXY(int x, int y) {

}

void LCD_Display(unsigned char ch[]) {

}

static void LCD_Init(void) {
	I2C2_Start();
	I2C2_CallAdress( (uint8_t) ((LCD_ADDRESS<<1) | I2C_WRITE));
	I2C2_Write(LCD_COMMAND);
	I2C2_Write(0x00); //Command stream
	I2C2_Write(0xAE); //Set display Off
	I2C2_Write(0xD5); //Set display clock divide ratio/oscillator frequency
	I2C2_Write(0x80);
	I2C2_Write(0xA8); //Set multiplex ratio
	I2C2_Write(0x3F);
	I2C2_Write(0xD3); //Set display offset
	I2C2_Write(0x00);
	I2C2_Write(0x40); //Set display start line
	I2C2_Write(0x8D); //Set charge pump
	I2C2_Write(0x14); //VCC generated by internal DC/DC circuit
	I2C2_Write(0xA1); //Set segment re-map 
	I2C2_Write(0xC0); //Set COM output scan direction
	I2C2_Write(0xDA); //Set COM pins hardware configuration
	I2C2_Write(0x12);
	I2C2_Write(0x81); //Set contrast control
	I2C2_Write(0xCF);
	I2C2_Write(0xD9); //Set pre-changed period
	I2C2_Write(0xF1);
	I2C2_Write(0xDB); //Set VCOMH Deselected level
	I2C2_Write(0x40);
	I2C2_Write(0xA4); //Set entire display on/off
	I2C2_Write(0xA6); //Set normal display 
	I2C2_Write(0x20); //Set memory address mode
	I2C2_Write(0x00); //Horizontal
	I2C2_Write(0xAF); //Set display on
	I2C2_Stop();
}

void LCD_Test(void) {
	LCD_Init();
	
	LCD_Command(Display, 'a');
	delay(MS);
}


/*******************************************************************************
 * EOF
 ******************************************************************************/
